cloud:
  aws:
    s3:
      bucket: ??? ?? ??? ?????
      region: ??? ??? ?????
      accessKey: IAM ??? accessKey? ?????
      secretKey: IAM ??? secretKey? ?????

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
